"""Add address to School model

Revision ID: 649fd759d5af
Revises: e2f3e85b82f0
Create Date: 2025-07-27 23:40:07.324535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649fd759d5af'
down_revision = 'e2f3e85b82f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
