"""Initial fresh migration

Revision ID: 810f1b683683
Revises: 
Create Date: 2025-07-27 02:38:31.528133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810f1b683683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_reference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'extracting', 'indexing', 'done', 'failed', name='processing_status_enum'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('processing_progress', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_reference')
    # ### end Alembic commands ###
